events { 
    worker_connections 1024; 
}

http {
    upstream backend_cluster {
        # --- ALGORITMA LEAST CONNECTION ---
        # Untuk mengaktifkan Least Connection, hilangkan tanda pagar (#) pada baris di bawah ini:
        # least_conn;

        # --- ALGORITMA ROUND ROBIN ---
        # Secara default, jika least_conn di atas dimatikan (diberi pagar), 
        # Nginx otomatis menggunakan algoritma statis Round Robin.

        # Daftarkan ketiga server backend kita
        server web_a:80;
        server web_b:80;
        server web_c:80;
    }

    server {
        listen 80;
        
        location / {
            # Teruskan semua lalu lintas HTTP ke grup backend_cluster
            proxy_pass http://backend_cluster;
        }
    }
}